/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desktopdirect_client_wintcsmng */

#ifndef _Included_com_desktopdirect_client_wintcsmng
#define _Included_com_desktopdirect_client_wintcsmng
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    init
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_desktopdirect_client_wintcsmng_init
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring,jstring, jstring, jint, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    initTCS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desktopdirect_client_wintcsmng_initTCS
  (JNIEnv *, jobject);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getDBMngParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desktopdirect_client_wintcsmng_getDBMngParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    beforeConnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_desktopdirect_client_wintcsmng_beforeConnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    powerupDesktop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_desktopdirect_client_wintcsmng_powerupDesktop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    launchDesktop
 * Signature: (Ljava/lang/String;IIIIIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_desktopdirect_client_wintcsmng_launchDesktop
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getHostsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_desktopdirect_client_wintcsmng_getHostsCount
  (JNIEnv *, jobject);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getHostHost
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desktopdirect_client_wintcsmng_getHostHost
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getHostDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desktopdirect_client_wintcsmng_getHostDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getHostTTL
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_desktopdirect_client_wintcsmng_getHostTTL
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_desktopdirect_client_wintcsmng
 * Method:    getHostState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_desktopdirect_client_wintcsmng_getHostState
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
